name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting & Goodbye
        run: |
            echo "Hello World!"
            echo "Good bye"

