name: Test and Deploy Project
on: [pull_request, workflow_dispatch]
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          policy: allow-list-policy
      - name: Get Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
        working-directory: "Starting-Project"
      - name: run tests
        run: npm test
        working-directory: "Starting-Project"

      - name: Call public API and echo result
        run: |
          response=$(curl -s "https://api.agify.io?name=michael")
          echo "API response: $response"
          age=$(echo "$response" | grep -o '"age":[0-9]*' | grep -o '[0-9]*')
          echo "Predicted age for Michael: $age"

  snyk:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Snyk test
        uses: snyk/actions/node@master
        with:
          args: --all-projects
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  pr-comment:
    needs: [test, snyk]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: "Tests have completed"

  deploy:
    needs: [test, snyk]
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          policy: allow-list-policy

      - name: Get Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
        working-directory: "Starting-Project"
      - name: Build project
        run: npm run build
        working-directory: "Starting-Project"
      - name: Deploy
        run: echo "Deploying"
