name: Test and DeployProject
on: [push, pull_request, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
              working-directory: "02 Starting Project"
            - name: run tests
              run: npm test
              working-directory: "02 Starting Project"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
              working-directory: "02 Starting Project"
            - name: Build project
              run: npm run build
              working-directory: "02 Starting Project"
            - name: Deploy
              run: echo "Deploying"